### ISSUE TITLE
Webpack configuration error

### ISSUE THREAD

**Issue by mrdivyansh** [Codebrahma/react-redux-boilerplate#3]
There is problem in running of server. Webpack is throwing miss-configuration error.

**Error log**
gumtree-frontend@1.0.0 start /home/divyansh/projects/gumtree-frontend
cross-env NODE_ENV=development node server

/home/divyansh/projects/gumtree-frontend/node_modules/webpack/lib/webpack.js:16
        throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration has an unknown property **'progress'**. These properties are valid:
  object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
  For typos: please correct them.
  For loader options: webpack 2 no longer allows custom properties in configuration.
   Loaders should be updated to allow passing options via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       options: {
         progress: ...
       }
     })
   }
  configuration.resolve has an unknown property **'packageMains'**. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
  **configuration.resolve.extensions[0]** should not be empty.
    at webpack (/home/divyansh/projects/gumtree-frontend/node_modules/webpack/lib/webpack.js:16:9)
    at addDevMiddlewares (/home/divyansh/projects/gumtree-frontend/server/middlewares/frontendMiddleware.js:12:20)
    at module.exports (/home/divyansh/projects/gumtree-frontend/server/middlewares/frontendMiddleware.js:69:5)
    at Object.<anonymous> (/home/divyansh/projects/gumtree-frontend/server/index.js:17:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

**My finding**
- `packageMains` seems unknown for Webpack. (refer. internals/webpack/webpack.base.babel.js:65)
- `progress` seems unknown for Webpack. (refer. internals/webpack/webpack.base.babel.js:73)
- `resolve.extensions[0]` should not be `''` (blank). (refer. internals/webpack/webpack.base.babel.js:60)

**Workaround fixes**
- Removed `packageMains`
- Removed `progress`
- Removed `resolve.extensions[0]`

I don't know whether my workaround is the solution or just workaround to tackle with issue.

**Comment by HaareeKrishna** [comment]
@mrdivyansh Thanks for pointing it out. Its because webpack version. We need to update to beta-22. I will do soon.

**Comment by HaareeKrishna** [comment]
Done! Thanks.
